// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umcociwvrzyqslkiejzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtY29jaXd2cnp5cXNsa2llanp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MzE1OTAsImV4cCI6MjA2NDQwNzU5MH0.S9YDPfMIbfeNTgA4vLpjX_tTCFFku7JuCh3YfketgNA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);